import asyncio
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from agents.analyst_agent import analyst_agent

def run_analysis_workflow(symbol: str, prompt: str) -> dict:
    """
    Runs the multi-agent workflow for a given stock symbol and prompt.
    Captures final response and trace logs.
    """
    symbol = symbol.strip().upper()
    app_name = "kitta_app"
    user_id = "user_kitta"
    # Create unique session for each query to avoid state bleeding
    session_id = f"session_{symbol}_{int(asyncio.get_event_loop().time() if asyncio.get_event_loop().is_running() else 0)}"
    
    session_service = InMemorySessionService()
    runner = Runner(agent=analyst_agent, app_name=app_name, session_service=session_service)
    
    full_prompt = f"[Target Stock Symbol: {symbol}] {prompt}"
    content = types.Content(role='user', parts=[types.Part(text=full_prompt)])
    
    # Run the ADK multi-agent workflow synchronously
    events = runner.run(user_id=user_id, session_id=session_id, new_message=content)
    
    final_response_text = ""
    traces = []
    
    for event in events:
        author = event.author if hasattr(event, 'author') else "system"
        
        # Build clean traces based on author activity
        if author == "analyst_agent":
            traces.append({
                "id": f"trace_{len(traces)+1}",
                "text": "[Master Agent] Coordinating sub-agent inputs...",
                "status": "info",
                "timestamp": str(event.created_at) if hasattr(event, 'created_at') else ""
            })
        elif author == "news_agent":
            traces.append({
                "id": f"trace_{len(traces)+1}",
                "text": "[News Agent] Fetching & summarizing news sentiment...",
                "status": "info",
                "timestamp": str(event.created_at) if hasattr(event, 'created_at') else ""
            })
        elif author == "chart_analyst":
            traces.append({
                "id": f"trace_{len(traces)+1}",
                "text": "[Chart Analyst] Generating indicators & trendlines...",
                "status": "info",
                "timestamp": str(event.created_at) if hasattr(event, 'created_at') else ""
            })
            
        if event.is_final_response() and event.content:
            final_response_text = event.content.parts[0].text.strip()
            
    if not final_response_text:
        final_response_text = "No response was generated by the Analyst Agent."
        
    traces.append({
        "id": f"trace_{len(traces)+1}",
        "text": "[Appraisal Engine] Finalized synthesis report.",
        "status": "success",
        "timestamp": ""
    })
    
    return {
        "analysis": final_response_text,
        "traces": traces,
        "symbol": symbol
    }
