import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from datetime import datetime

def generate_technical_chart(csv_path, output_image_name='nepse_analysis.png', view_days=250):
    """
    Reads scraped historical stock/index data, calculates technical metrics,
    automatically detects trendlines, and exports a high-quality multi-panel chart.
    
    :param csv_path: Path to the CSV file generated by your scraper.
    :param output_image_name: Filename for the saved visualization chart.
    :param view_days: Number of recent trading days to look at in the chart.
    """
    # 1. Load and sort the data
    df = pd.read_csv(csv_path)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date').reset_index(drop=True)
    
    # 2. Calculate Technical Indicators
    # Exponential Moving Averages (EMA)
    df['EMA20'] = df['Close'].ewm(span=20, adjust=False).mean()
    df['EMA50'] = df['Close'].ewm(span=50, adjust=False).mean()
    
    # Relative Strength Index (RSI)
    delta = df['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    ema_gain = gain.ewm(com=13, adjust=False).mean()
    ema_loss = loss.ewm(com=13, adjust=False).mean()
    rs = ema_gain / ema_loss
    df['RSI'] = 100 - (100 / (1 + rs))
    
    # Moving Average Convergence Divergence (MACD)
    df['EMA12'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['EMA26'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = df['EMA12'] - df['EMA26']
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist'] = df['MACD'] - df['MACD_Signal']
    
    # 3. Filter for the recent window to keep the visualization clean
    chart_df = df.tail(view_days).copy().reset_index(drop=True)
    dates = chart_df['Date']
    prices = chart_df['Close'].values
    x = np.arange(len(prices))
    
    # 4. Automated Peak & Trough Detection for Trendlines
    # 'distance' sets minimum candles between pivots; 'prominence' avoids tiny noise ripples
    peaks, _ = find_peaks(prices, distance=15, prominence=10)
    troughs, _ = find_peaks(-prices, distance=15, prominence=10)
    
    # 5. Build Subplots Layout
    fig, axes = plt.subplots(4, 1, figsize=(15, 12), sharex=True, 
                             gridspec_kw={'height_ratios': [4, 1, 1.5, 1.5]})
    
    # --- PANEL 1: Main Price & Trendline Overlay ---
    ax0 = axes[0]
    ax0.plot(x, chart_df['Close'], label='Close Price', color='blue', linewidth=1.5)
    ax0.plot(x, chart_df['EMA20'], label='20 EMA', color='orange', linestyle='--', linewidth=1)
    ax0.plot(x, chart_df['EMA50'], label='50 EMA', color='magenta', linestyle='--', linewidth=1)
    
    # Generate and draw the Resistance Trendline (connecting last 2 peaks)
    if len(peaks) >= 2:
        p1, p2 = peaks[-2], peaks[-1]
        m_res = (prices[p2] - prices[p1]) / (p2 - p1)
        c_res = prices[p1] - m_res * p1
        ax0.plot(x[p1:], m_res * x[p1:] + c_res, color='red', linestyle='-', linewidth=2, label='Resistance Trendline')
        ax0.scatter(peaks, prices[peaks], color='red', marker='^', s=40, label='Local Peaks', zorder=5)
        
    # Generate and draw the Support Trendline (connecting last 2 troughs)
    if len(troughs) >= 2:
        t1, t2 = troughs[-2], troughs[-1]
        m_sup = (prices[t2] - prices[t1]) / (t2 - t1)
        c_sup = prices[t1] - m_sup * t1
        ax0.plot(x[t1:], m_sup * x[t1:] + c_sup, color='green', linestyle='-', linewidth=2, label='Support Trendline')
        ax0.scatter(troughs, prices[troughs], color='green', marker='v', s=40, label='Local Troughs', zorder=5)
        
    symbol_name = csv_path.split('_')[0].upper()
    ax0.set_title(f"{symbol_name} Historical Technical Analysis Chart", fontsize=14, fontweight='bold')
    ax0.set_ylabel("Price (NRS)", fontsize=11)
    ax0.legend(loc='upper left')
    ax0.grid(True, linestyle=':', alpha=0.6)
    
    # --- PANEL 2: Colored Volume Bars ---
    ax1 = axes[1]
    # Color bars green if close >= open, else red
    volume_colors = ['green' if chart_df['Close'][i] >= chart_df['Open'][i] else 'red' for i in range(len(chart_df))]
    ax1.bar(x, chart_df['Volume'], color=volume_colors, width=0.8, alpha=0.7)
    ax1.set_ylabel("Volume", fontsize=11)
    ax1.grid(True, linestyle=':', alpha=0.6)
    
    # --- PANEL 3: RSI Indicator ---
    ax2 = axes[2]
    ax2.plot(x, chart_df['RSI'], color='purple', label='RSI (14)')
    ax2.axhline(70, color='red', linestyle=':', linewidth=1)
    ax2.axhline(30, color='green', linestyle=':', linewidth=1)
    ax2.fill_between(x, 70, 30, color='purple', alpha=0.05) # Highlight neutral band
    ax2.set_ylabel("RSI", fontsize=11)
    ax2.set_ylim(10, 90)
    ax2.legend(loc='upper left')
    ax2.grid(True, linestyle=':', alpha=0.6)
    
    # --- PANEL 4: MACD Lines & Histogram ---
    ax3 = axes[3]
    ax3.plot(x, chart_df['MACD'], color='blue', label='MACD')
    ax3.plot(x, chart_df['MACD_Signal'], color='orange', label='Signal Line')
    hist_colors = ['green' if val >= 0 else 'red' for val in chart_df['MACD_Hist']]
    ax3.bar(x, chart_df['MACD_Hist'], color=hist_colors, width=0.8, alpha=0.5, label='Histogram')
    ax3.set_ylabel("MACD", fontsize=11)
    ax3.legend(loc='upper left')
    ax3.grid(True, linestyle=':', alpha=0.6)
    
    # Format x-axis timestamps uniformly
    label_step = len(chart_df) // 8
    ax3.set_xticks(x[::label_step])
    ax3.set_xticklabels([d.strftime('%Y-%m-%d') for d in dates[::label_step]], rotation=30, ha='right')
    ax3.set_xlabel("Date", fontsize=11)
    
    # 6. Optimize spacing and export image file
    plt.tight_layout()
    plt.savefig(output_image_name, dpi=150)
    plt.close()
    print(f"✨ Chart saved successfully to: {output_image_name}")

# ==========================================
# Example Execution Setup
# ==========================================
if __name__ == "__main__":
    # If your scraper saves data to 'NEPSE_historical_data.csv', pass it here:
    generate_technical_chart("NEPSE_historical_data.csv")
    pass