import asyncio
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from app.agents.analyst_agent import analyst_agent

def run_analysis_workflow(symbol: str, prompt: str) -> dict:
    """
    Runs the multi-agent workflow for a given stock symbol and prompt.
    Captures final response and trace logs.
    """
    symbol = symbol.strip().upper()
    app_name = "kitta_app"
    user_id = "user_kitta"
    import time
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
    session_id = f"session_{symbol}_{int(time.time())}"
    session_service = InMemorySessionService()
    session_service.create_session_sync(app_name=app_name, user_id=user_id, session_id=session_id)
    runner = Runner(agent=analyst_agent, app_name=app_name, session_service=session_service)
    
    from app.agents.tools import free_web_search
    import requests
    news_data = free_web_search(symbol)
    try:
        res = requests.get(f"http://localhost:8002/api/quant/{symbol}", timeout=10)
        quant_data = res.json() if res.status_code == 200 else "Unavailable"
        if isinstance(quant_data, dict):
            quant_data.pop("historical_prices", None)
            quant_data = json.dumps(quant_data, indent=2)
    except:
        quant_data = "Error fetching quant data"
    
    full_prompt = f"""Target Stock Symbol: {symbol}
User Query: "{prompt}"

CRITICAL INSTRUCTION: First, analyze the User Query. 
1. If the query asks for stock analysis, trend, or details about the stock {symbol}, you MUST call the `chart_analyst_agent` tool to gather technical data, then provide a comprehensive appraisal synthesizing the chart data, REAL-TIME NEWS, and QUANT METRICS below.
2. If the query is just conversational or a general question (e.g., "hi", "how are you"), just answer the query directly and naturally in a friendly tone without generating a stock report.

--- LATEST NEWS DATA FOR {symbol} ---
{news_data}
------------------------

--- QUANT METRICS (Dashboard Data) ---
{quant_data}
------------------------
"""
    content = types.Content(role='user', parts=[types.Part(text=full_prompt)])
    
    # Run the ADK multi-agent workflow synchronously
    events = runner.run(user_id=user_id, session_id=session_id, new_message=content)
    
    final_response_text = ""
    traces = []
    
    for event in events:
        author = event.author if hasattr(event, 'author') else "system"
        
        # Build clean traces based on author activity
        if author == "analyst_agent":
            traces.append({
                "id": f"trace_{len(traces)+1}",
                "text": "[Master Agent] Coordinating sub-agent inputs...",
                "status": "info",
                "timestamp": str(event.created_at) if hasattr(event, 'created_at') else ""
            })
        elif author == "news_agent":
            traces.append({
                "id": f"trace_{len(traces)+1}",
                "text": "[News Agent] Fetching & summarizing news sentiment...",
                "status": "info",
                "timestamp": str(event.created_at) if hasattr(event, 'created_at') else ""
            })
        elif author == "chart_analyst":
            traces.append({
                "id": f"trace_{len(traces)+1}",
                "text": "[Chart Analyst] Generating indicators & trendlines...",
                "status": "info",
                "timestamp": str(event.created_at) if hasattr(event, 'created_at') else ""
            })
            
        if event.is_final_response() and event.content:
            final_response_text = event.content.parts[0].text.strip()
            
        with open("events_debug.log", "a") as f:
            f.write(f"Event: {str(event)}\n")
            
    if not final_response_text:
        final_response_text = "No response was generated by the Analyst Agent."
        
    traces.append({
        "id": f"trace_{len(traces)+1}",
        "text": "[Appraisal Engine] Finalized synthesis report.",
        "status": "success",
        "timestamp": ""
    })
    
    return {
        "analysis": final_response_text,
        "traces": traces,
        "symbol": symbol
    }

import json

async def stream_analysis_workflow(symbol: str, prompt: str):
    """
    Runs the multi-agent workflow for a given stock symbol and prompt,
    yielding Server-Sent Events (SSE) for streaming to the UI.
    """
    try:
        symbol = symbol.strip().upper()
        app_name = "kitta_app"
        user_id = "user_kitta"
        import time
        
        session_id = f"session_{symbol}_{int(time.time())}"
        session_service = InMemorySessionService()
        session_service.create_session_sync(app_name=app_name, user_id=user_id, session_id=session_id)
        runner = Runner(agent=analyst_agent, app_name=app_name, session_service=session_service)
        
        full_prompt = f"""Target Stock Symbol: {symbol}
User Query: "{prompt}"

CRITICAL INSTRUCTION: You MUST call the `news_agent` tool and the `chart_analyst` tool right now to gather data. After gathering data from BOTH tools, directly answer the User Query."""
        content = types.Content(role='user', parts=[types.Part(text=full_prompt)])
        
        yield f"data: {json.dumps({'type': 'start', 'symbol': symbol})}\n\n"
        
        from app.services.chart_engine import generate_technical_chart
        yield f"data: {json.dumps({'type': 'reasoning', 'text': 'System is initializing chart generation engine...' + chr(10)})}\n\n"
        
        # Run synchronous chart generator in thread to avoid blocking asyncio loop
        await asyncio.to_thread(generate_technical_chart, symbol, static_dir="app/static")
        yield f"data: {json.dumps({'type': 'reasoning', 'text': 'System successfully generated the technical chart.' + chr(10)})}\n\n"
        
        # Manually invoke news gathering to bypass LLM tool limitations
        yield f"data: {json.dumps({'type': 'reasoning', 'text': 'News Agent is scanning the live web for real-time data...' + chr(10)})}\n\n"
        
        from app.agents.tools import free_web_search
        import requests
        
        # Concurrently fetch news and quant metrics
        async def fetch_quant():
            try:
                res = await asyncio.to_thread(requests.get, f"http://localhost:8002/api/quant/{symbol}", timeout=10)
                if res.status_code == 200:
                    data = res.json()
                    data.pop("historical_prices", None) # Remove massive array
                    return json.dumps(data, indent=2)
                return "Quant data not available."
            except Exception as e:
                return f"Quant error: {str(e)}"
                
        news_data, quant_data = await asyncio.gather(
            asyncio.to_thread(free_web_search, symbol),
            fetch_quant()
        )
        
        yield f"data: {json.dumps({'type': 'reasoning', 'text': 'News Agent successfully compiled all recent web news and quantitative metrics.' + chr(10)})}\n\n"
        yield f"data: {json.dumps({'type': 'reasoning', 'text': 'System is waking up the Master Analyst for synthesis...' + chr(10)})}\n\n"
        
        full_prompt = f"""Target Stock Symbol: {symbol}
User Query: "{prompt}"

CRITICAL INSTRUCTION: First, analyze the User Query. 
1. If the query asks for stock analysis, trend, or details about the stock {symbol}, you MUST call the `chart_analyst_agent` tool to gather technical data, then provide a comprehensive appraisal synthesizing the chart data, REAL-TIME NEWS, and QUANT METRICS below.
2. If the query is just conversational or a general question (e.g., "hi", "how are you"), just answer the query directly and naturally in a friendly tone without generating a stock report.

--- LATEST NEWS DATA FOR {symbol} ---
{news_data}
------------------------

--- QUANT METRICS (Dashboard Data) ---
{quant_data}
------------------------
"""
        content = types.Content(role='user', parts=[types.Part(text=full_prompt)])
        
        def clean_author(name):
            if name == "news_agent": return "News Agent"
            if name == "chart_analyst" or name == "chart_analyst_agent": return "Chart Analyst"
            if name == "analyst_agent": return "Master Analyst"
            return name.replace("_", " ").title()

        async for event in runner.run_async(user_id=user_id, session_id=session_id, new_message=content):
            author = getattr(event, 'author', 'system')
            clean_name = clean_author(author)
            trace_text = f"{clean_name} is processing the data..."
            
            # Show all tool calls
            if hasattr(event, 'content') and event.content and hasattr(event.content, 'parts'):
                for part in event.content.parts:
                    if hasattr(part, 'function_call') and part.function_call:
                        fn_name = part.function_call.name
                        if "chart" in fn_name:
                            trace_text = f"{clean_name} is running technical analysis on the chart..."
                        elif "news" in fn_name or "search" in fn_name:
                            trace_text = f"{clean_name} is fetching latest market sentiment..."
                        else:
                            trace_text = f"{clean_name} is using a specialized tool..."
                        
            yield f"data: {json.dumps({'type': 'reasoning', 'text': trace_text + chr(10)})}\n\n"
            
            # Stream text chunks or final responses
            if hasattr(event, 'content') and event.content and hasattr(event.content, 'parts'):
                for part in event.content.parts:
                    if hasattr(part, 'text') and part.text:
                        if event.is_final_response() and author == "analyst_agent":
                            yield f"data: {json.dumps({'type': 'content', 'text': part.text})}\n\n"
                        else:
                            yield f"data: {json.dumps({'type': 'reasoning', 'text': f'{clean_name} is synthesizing insights...' + chr(10)})}\n\n"
                            
            if getattr(event, 'error_message', None):
                err_msg = getattr(event, 'error_message')
                yield f"data: {json.dumps({'type': 'reasoning', 'text': f'{clean_name} encountered an error: {err_msg}' + chr(10)})}\n\n"
                yield f"data: {json.dumps({'type': 'content', 'text': f'\n\n**Agent System Error:** `{err_msg}`\n\nThe intelligence backend encountered a critical error while computing the analysis. Please check your API keys and configuration.'})}\n\n"
                        
        yield f"data: {json.dumps({'type': 'reasoning', 'text': 'Appraisal Engine finalized the synthesis report.' + chr(10)})}\n\n"
    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        print(f"Error during agent stream: {tb}")
        err_msg = f"\n\n**Agent System Error:** `{str(e)}`\n\nThe intelligence backend encountered a critical error while computing the analysis. Please check the backend logs."
        yield f"data: {json.dumps({'type': 'reasoning', 'text': '[Appraisal Engine] ERROR: Workflow crashed!' + chr(10)})}\n\n"
        yield f"data: {json.dumps({'type': 'content', 'text': err_msg})}\n\n"
        
    yield f"data: {json.dumps({'type': 'done'})}\n\n"
